### ISSUE TITLE
镜像报错，无法启动

### ISSUE THREAD

**Issue by yjps** [LiHang941/clash-tproxy#1]
`docker run --name clash -d -v /etc/docker/clash/config.yaml:/root/.config/clash/config.yaml  --network vlan --ip 10.0.0.3 --cap-add=NET_ADMIN lihang941/clash-tproxy`

```
root@docker:/etc/docker/clash# docker logs --details clash
sysctl: error setting key 'net.ipv4.ip_forward': Read-only file system
```

请问要怎么解决呢？谢谢！

**Comment by yjps** [comment]
通过加入  --privileged 解决此报错

**Comment by LiHang941** [comment]
直接使用docker-compose.yaml
